name: Build x64 Release

on:
  workflow_dispatch: {}        # 手動実行トリガー
  # 以下の push を不要なら削って構いません
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build x64 Release
        run: |
          dotnet build --configuration Release -r win-x64 --no-self-contained

      - name: Publish x64 Release (framework-dependent)
        run: |
          dotnet publish .\DS4Windows\DS4WinWPF.csproj -c Release -r win-x64 --self-contained false /p:PublishSingleFile=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ds4windows-x64-publish
          path: DS4Windows\bin\Release\net8.0\win-x64\publish\
